#!/usr/bin/env python3
r"""Producer: the Ch2 phrase exhibit and the last small macros.

Emits tables/tab_p1_phrases.tex (top phrases of the warmth and teaching
models, full-sample descriptive refit at the harness's chosen penalty) and
snippets/exhibit_numbers.tex: \OwnVoiceMax (largest own-voice enacted cell),
\CrossWireRaw/\CrossWireNet (report -> espoused strictness before/after
partialling enacted), \PVPredWarmth/\PVPredWarmthN (national predicted
warmth vs Parent View warmth, training schools excluded).
"""
from __future__ import annotations

from pathlib import Path
import sys

import numpy as np
import pandas as pd

from fix_tables import move_caption_below

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))
CONTROLS = ["fsm", "eal", "ks2", "years_since_ofsted"]


def main() -> None:
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import Ridge

    spine = pd.read_csv(ROOT / "text_spine.csv")
    spine["urn"] = spine["urn"].astype(int)
    ds = pd.read_csv(ROOT / "analysis_dataset.csv", low_memory=False)
    ds["urn"] = pd.to_numeric(ds["urn"], errors="coerce")
    ds = ds.dropna(subset=["urn"]).set_index("urn")
    ctrl = pd.DataFrame({c: pd.to_numeric(
        ds[c].astype(str).str.rstrip("%"), errors="coerce")
        for c in CONTROLS})

    vis = spine[spine["visited"] & spine["has_all3"]]
    urns = vis["urn"].to_numpy(int)
    texts = [(ROOT / "text_corpus_r2" / "ofsted" / f"{u}.txt"
              ).read_text(encoding="utf-8") for u in urns]
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 2),
                          min_df=5, max_df=0.9, sublinear_tf=True)
    X = np.asarray(vec.fit_transform(texts).todense())
    vocab = np.array(vec.get_feature_names_out())
    C = ctrl.reindex(urns).to_numpy(float)
    ok = ~np.isnan(C).any(axis=1)

    yv = spine.set_index("urn")
    cols = {"Warmth": "gs_warmth_enacted", "Teaching": "gs_teaching_enacted"}
    panels = {}
    for name, col in cols.items():
        y = yv.loc[urns, col].to_numpy(float)
        m = ok & ~np.isnan(y)
        A = np.column_stack([np.ones(int(m.sum())), C[m]])
        beta, *_ = np.linalg.lstsq(A, y[m], rcond=None)
        r = Ridge(alpha=0.01, fit_intercept=True).fit(X[m], y[m] - A @ beta)
        coef = np.asarray(r.coef_).ravel()
        drop = np.array([any(ch.isdigit() for ch in v) for v in vocab])
        coef2 = np.where(drop, 0, coef)
        panels[name] = (vocab[np.argsort(coef2)[::-1][:10]],
                        vocab[np.argsort(coef2)[:10]])

    rows = []
    for i in range(10):
        rows.append(" & ".join([
            panels["Warmth"][0][i], panels["Warmth"][1][i],
            panels["Teaching"][0][i], panels["Teaching"][1][i]]) + r" \\")
    table = (
        "% generated by make_ch2_exhibits.py -- do not edit\n"
        "\\begin{table}[htbp]\n\\centering\n"
        "\\caption{What the prediction models read: the ten phrases with the "
        "largest positive and negative weights in the warmth and teaching "
        "models (inspection reports, demographics removed from the target). "
        "Full-sample descriptive fits at the penalty the tested models "
        "chose.}\n"
        "\\label{tab:p1_phrases}\n"
        "{\\small\\begin{tabular}{llll}\n\\toprule\n"
        "\\multicolumn{2}{c}{Warmth} & \\multicolumn{2}{c}{Teaching} \\\\\n"
        "\\cmidrule(lr){1-2}\\cmidrule(lr){3-4}\n"
        "Raises & Lowers & Raises & Lowers \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}}\n\\end{table}\n")
    table, _ = move_caption_below(table)
    (HERE / "tables" / "tab_p1_phrases.tex").write_text(
        table, encoding="utf-8")

    # ---- macros ----
    res = pd.read_csv(ROOT / "text_prediction_results_r2_minilm.csv")
    own = res[(res["leg"] == "deconf") & (res["sample"] == "enacted")
              & (res["arm"] == "tfidf") & res["block"].isin(["bp", "web"])]
    own_max = own["loo_r"].max()

    both = spine[spine["has_all3"] & spine["interviewed"] & spine["visited"]]
    u2 = both["urn"].to_numpy(int)
    tx2 = [(ROOT / "text_corpus_r2" / "ofsted" / f"{u}.txt"
            ).read_text(encoding="utf-8") for u in u2]
    X2 = np.asarray(TfidfVectorizer(
        stop_words="english", ngram_range=(1, 2), min_df=5, max_df=0.9,
        sublinear_tf=True).fit_transform(tx2).todense())
    from text_prediction_models import FoldCache, metrics
    esp = yv.loc[u2, "gs_strictness_espoused"].to_numpy(float)
    ena = yv.loc[u2, "gs_strictness_enacted"].to_numpy(float)
    C2 = ctrl.reindex(u2).to_numpy(float)
    K = X2 @ X2.T
    m1 = ~np.isnan(esp) & ~np.isnan(C2).any(axis=1)
    A1 = np.column_stack([np.ones(int(m1.sum())), C2[m1]])
    b1, *_ = np.linalg.lstsq(A1, esp[m1], rcond=None)
    y1 = esp[m1] - A1 @ b1
    p1, _ = FoldCache(K[np.ix_(m1, m1)]).loo(y1)
    r_raw = metrics(y1, p1)[0]
    m2 = m1 & ~np.isnan(ena)
    A2 = np.column_stack([np.ones(int(m2.sum())), C2[m2], ena[m2]])
    b2, *_ = np.linalg.lstsq(A2, esp[m2], rcond=None)
    y2 = esp[m2] - A2 @ b2
    p2, _ = FoldCache(K[np.ix_(m2, m2)]).loo(y2)
    r_net = metrics(y2, p2)[0]

    pred = pd.read_csv(ROOT / "national_warmth_text_predictions.csv")
    mm = pred[~pred["in_training"]].merge(
        ds.reset_index()[["urn", "pv_warmth"]], on="urn")
    pv = pd.to_numeric(mm["pv_warmth"], errors="coerce")
    okp = pv.notna()
    r_pv = np.corrcoef(mm.loc[okp, "warmth_text_pred"], pv[okp])[0, 1]

    def f(x):
        return ("+" if x >= 0 else "") + f"{x:.2f}"

    macros = {
        "OwnVoiceMax": f(own_max),
        "CrossWireRaw": f(r_raw),
        "CrossWireNet": f(r_net),
        "PVPredWarmth": f(r_pv),
        "PVPredWarmthN": f"{int(okp.sum()):,}",
    }
    lines = ["% generated by make_ch2_exhibits.py -- do not edit"]
    for k, v in macros.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    (HERE / "snippets" / "exhibit_numbers.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")
    print("exhibit table + macros written:", macros)


if __name__ == "__main__":
    main()
