#!/usr/bin/env python3
"""Producer: the Chapter 3 timing-checks table (tab_timing_checks.tex).

Collects into one float the timing checks that previously lived only in
prose: Panel A, the pre-pandemic placebo legs and their contemporaneous
twin (placebo_2019_results.csv, written by placebo_2019_analysis.py);
Panel B, the head-continuity split of the primary specification
(timing_checks_results.csv, written by ch3_timing_checks.py). The formal
stacked placebo-vs-contemporaneous difference tests (same file) and the
report-age x strictness interaction (band_extras_results.csv, written by
analyse_band_extras.py) are reported in the notes.

Rerun the two root scripts first if their CSVs are stale.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from fix_tables import caption_to_title, move_caption_above

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def stars(p: float) -> str:
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.1 else ""


def main() -> None:
    pl = pd.read_csv(ROOT / "placebo_2019_results.csv")
    tc = pd.read_csv(ROOT / "timing_checks_results.csv")
    be = pd.read_csv(ROOT / "band_extras_results.csv")

    def pl_cells(spec):
        d = pl[pl["spec"] == spec].set_index("term")
        w = d.loc["z_gs_warmth_enacted"]
        s = d.loc["z_gs_strictness_enacted"]
        return w, s

    def row(label, w, s, n):
        top = (f"{label} & {w['b']:+.3f}{stars(w['p'])} & ({w['se']:.3f}) & "
               f"{s['b']:+.3f}{stars(s['p'])} & ({s['se']:.3f}) & {n} \\\\")
        return top

    rows = ["\\multicolumn{6}{l}{\\textit{Panel A: results from before the fieldwork "
            "(outcome is 2018/19 Progress 8 unless stated)}} \\\\",
            "\\addlinespace[2pt]"]
    w, s = pl_cells("placebo_era_controls")
    rows.append(row("2018/19 P8, era intake controls", w, s, int(w["n"])))
    w, s = pl_cells("placebo_current_controls")
    rows.append(row("2018/19 P8, all-current controls", w, s, int(w["n"])))
    w, s = pl_cells("contemp_on_placebo_sample")
    rows.append(row("Contemporaneous P8, same schools", w, s, int(w["n"])))

    rows += ["\\addlinespace[6pt]",
             "\\multicolumn{6}{l}{\\textit{Panel B: same or changed headteacher "
             "(contemporaneous P8, primary specification)}} \\\\",
             "\\addlinespace[2pt]"]
    hc = tc[tc["block"] == "head_continuity"]
    for spec, label in (("continuing_head",
                         "Same head, Sept 2022 and July 2025"),
                        ("changed_head",
                         "Head changed between those dates")):
        d = hc[hc["spec"] == spec].set_index("term")
        rows.append(row(label, d.loc["warmth"], d.loc["strictness"],
                        int(d.loc["warmth", "n"])))

    st = tc[tc["block"] == "stacked_test"].set_index(["spec", "term"])
    p_w = float(st.loc[("era_controls_vs_current", "diff_warmth"), "p"])
    p_s = float(st.loc[("era_controls_vs_current", "diff_strictness"), "p"])
    p_wc = float(st.loc[("current_controls_both", "diff_warmth"), "p"])
    p_sc = float(st.loc[("current_controls_both", "diff_strictness"), "p"])
    age = be[be["term"] == "score_x_age"].iloc[0]
    age_n = f"{int(age['n']):,}".replace(",", "{,}")

    table = (
        "% generated by make_ch3_checks_table.py -- do not edit\n"
        "\\begin{table}[htbp]\n\\centering\n\\small\n"
        "\\begin{tabular}{lccccc}\n\\toprule\n"
        " & Warmth & (se) & Strictness & (se) & $n$ \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{Timing checks on the visited-school estimates. Every row "
        "regresses the stated outcome on standardised enacted warmth and "
        "strictness with the full control set plus pre-COVID inspection-grade indicators (grades 1--2 pooled base; schools with a missing grade drop), HC3 standard "
        "errors, late-entry schools excluded; each row reports its own "
        "estimation-sample $n$. Panel A relates the culture scores to "
        "results from a cohort "
        "the visits never observed: the 2018/19 school-level Progress 8, "
        "with the intake controls either swapped to that era's values (KS2 "
        "APS of the GCSE cohort and FSM share) or held at current values, "
        "beside the contemporaneous outcome on the same 93 schools. Panel B "
        "splits the primary specification by whether the school had the "
        "same headteacher in the 1 September 2022 and 1 July 2025 GIAS "
        "extracts, that is, from the first outcome cohort's final year to "
        "the end of the visit window.}\n"
        "\\label{tab:timing_checks}\n"
        "\\begin{minipage}{\\linewidth}\n\\smallskip\n"
        "\\footnotesize\\textit{Notes:} Standard errors in parentheses. "
        "$^{*}$ \\(p<0.10\\), $^{**}$ \\(p<0.05\\), $^{***}$ \\(p<0.01\\). "
        "The headteacher-change flag covers every estimation-sample school.\n"
        "\\end{minipage}\n\\end{table}\n")
    table, _ = move_caption_above(table)
    table = caption_to_title(
        table, "Timing checks on the visited-school estimates")
    out = HERE / "tables" / "tab_timing_checks.tex"
    out.write_text(table, encoding="utf-8")
    print(f"wrote thesis/tables/{out.name}")


if __name__ == "__main__":
    main()
