#!/usr/bin/env python3
r"""Producer: the Chapter 3 national-legs table, the identity exploratory
table, and their macros.

Reads national_{warmth,teaching,strictness}_regression_results.csv and
identity_exploratory_results.csv; writes tables/tab_national_legs.tex,
tables/tab_identity.tex and snippets/national_numbers.tex (macros
\NatW, \NatWGrade, \NatT, \NatS, \NatSGrade, \NatWPreTwo, ..., \IdPed,
\IdEth, \IdFaithCentral). Registered in check_pipeline stage-5.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from fix_tables import caption_to_title, move_caption_below

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def stars(p):
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.1 else ""


def main() -> None:
    legs = {}
    for name in ("warmth", "teaching", "strictness"):
        legs[name] = pd.read_csv(
            ROOT / f"national_{name}_regression_results.csv")

    def cell(name, spec_contains):
        d = legs[name]
        r = d[d["spec"].str.contains(spec_contains, regex=False)].iloc[0]
        return r

    m = {}
    rows = []
    order = [("warmth", "Warmth", "prediction model"),
             ("teaching", "Teaching", "prediction model"),
             ("strictness", "Strictness", "mark scheme")]
    def tex_n(n):
        return f"{int(n):,}".replace(",", "{,}")

    for key, label, inst in order:
        ng = cell(key, "no grade") if key != "strictness" else cell(key, "no grade control")
        wg = cell(key, "with grade")
        pre = cell(key, "pre-2022")
        m[f"Nat{label[0]}"] = f"{ng['b']:+.3f}"
        m[f"Nat{label[0]}Grade"] = f"{wg['b']:+.3f}"
        m[f"Nat{label[0]}Pre"] = f"{pre['b']:+.3f}"
        # generated-regressor bootstrap interval (warmth and teaching legs
        # only; the marking-scheme bands estimate nothing from the sample,
        # so there is no generated regressor to bootstrap)
        boot = legs[key][legs[key]["spec"].str.contains("bootstrap", na=False)]
        if len(boot):
            bt = boot.iloc[0]
            m[f"Nat{label[0]}BootLo"] = f"{bt['ci_lo']:+.3f}"
            m[f"Nat{label[0]}BootHi"] = f"{bt['ci_hi']:+.3f}"
            ci = f"[{bt['ci_lo']:+.3f}, {bt['ci_hi']:+.3f}]"
        else:
            ci = "---"
        rows.append(
            f"{label} & {inst} & {ng['b']:+.3f}{stars(ng['p'])} & "
            f"({ng['se']:.3f}) & {wg['b']:+.3f}{stars(wg['p'])} & "
            f"{pre['b']:+.3f}{stars(pre['p'])} & {ci} \\\\")
        # each column's own estimation-sample n, read from its result row
        rows.append(
            f" & & $n={tex_n(ng['n'])}$ & & $n={tex_n(wg['n'])}$ & "
            f"$n={tex_n(pre['n'])}$ & \\\\")

    table = (
        "% generated by make_ch3_national_tables.py -- do not edit\n"
        "\\begin{table}[htbp]\n\\centering\n"
        "\\caption{The three national legs: Progress 8 on each text-derived "
        "culture score, one standard deviation units, HC3 standard errors. "
        "Every school's warmth and teaching predictions come from models "
        "that never saw it; the strictness bands come from the frozen "
        "one-page mark scheme applied once per report. The last column "
        "is the 95 per cent generated-regressor bootstrap interval for the "
        "full-controls coefficient (B=500 over the training fit); the "
        "mark-scheme bands estimate nothing from the sample, so the "
        "strictness leg has none. Each column reports its own "
        "estimation-sample $n$.}\n"
        "\\label{tab:national_legs}\n"
        "\\begin{tabular}{llccccc}\n\\toprule\n"
        " & Instrument & \\multicolumn{2}{c}{Full controls} & +Grade & "
        "Pre-2022 & 95\\% CI \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\begin{minipage}{\\linewidth}\n\\smallskip\n"
        "\\footnotesize\\textit{Notes:} Standard errors in parentheses. "
        "$^{*}$ \\(p<0.10\\), $^{**}$ \\(p<0.05\\), $^{***}$ \\(p<0.01\\).\n"
        "\\end{minipage}\n\\end{table}\n")
    table, _ = move_caption_below(table)
    table = caption_to_title(
        table, "The three national legs", keep_first=True)
    (HERE / "tables" / "tab_national_legs.tex").write_text(
        table, encoding="utf-8")

    ide = pd.read_csv(ROOT / "identity_exploratory_results.csv")
    irows = []
    for pred, term, label in [
            ("traditional pedagogy", "trad_ped", "Traditional pedagogy"),
            ("traditional ethos", "trad_eth", "Traditional ethos"),
            ("faith prominence", "fp_central", "Faith central (vs none)"),
            ("faith prominence", "fp_present", "Faith present (vs none)")]:
        ng = ide[(ide["predictor"].str.startswith(pred))
                 & (ide["predictor"].str.contains("no grade"))
                 & (ide["term"] == term)].iloc[0]
        wg = ide[(ide["predictor"].str.startswith(pred))
                 & (ide["predictor"].str.contains("with grade"))
                 & (ide["term"] == term)].iloc[0]
        irows.append(f"{label} & {ng['b']:+.3f}{stars(ng['p'])} & "
                     f"({ng['se']:.3f}) & {wg['b']:+.3f}{stars(wg['p'])} & "
                     f"{int(ng['n']):,} \\\\")
    m["IdPed"] = f"{ide[(ide['term']=='trad_ped') & (ide['predictor'].str.contains('no grade'))]['b'].iloc[0]:+.3f}"
    m["IdEth"] = f"{ide[(ide['term']=='trad_eth') & (ide['predictor'].str.contains('no grade'))]['b'].iloc[0]:+.3f}"
    m["IdFaithCentral"] = f"{ide[(ide['term']=='fp_central') & (ide['predictor'].str.contains('no grade'))]['b'].iloc[0]:+.3f}"

    itable = (
        "% generated by make_ch3_national_tables.py -- do not edit\n"
        "\\begin{table}[htbp]\n\\centering\n"
        "\\caption{Exploratory: website identity measures and Progress 8, "
        "full controls, HC3. Traditional pedagogy and ethos are binary "
        "indicators; faith prominence enters as categories against "
        "``none'', with religious-character status controlled.}\n"
        "\\label{tab:identity}\n"
        "\\begin{tabular}{lcccc}\n\\toprule\n"
        " & Full controls & (se) & +Grade & $n$ \\\\\n\\midrule\n"
        + "\n".join(irows) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\begin{minipage}{\\linewidth}\n\\smallskip\n"
        "\\footnotesize\\textit{Notes:} Standard errors in parentheses. "
        "$^{*}$ \\(p<0.10\\), $^{**}$ \\(p<0.05\\), $^{***}$ \\(p<0.01\\).\n"
        "\\end{minipage}\n\\end{table}\n")
    itable, _ = move_caption_below(itable)
    itable = caption_to_title(
        itable, "Website identity measures and Progress~8 (exploratory)",
        keep_first=True)
    (HERE / "tables" / "tab_identity.tex").write_text(itable, encoding="utf-8")

    lines = ["% generated by make_ch3_national_tables.py -- do not edit"]
    for k, v in m.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    (HERE / "snippets" / "national_numbers.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote tab_national_legs, tab_identity, {len(m)} macros")


if __name__ == "__main__":
    main()
