#!/usr/bin/env python3
"""Producer: the Chapter 2 grid table and every grid/prediction macro.

Reads rubric_grid_analysis.csv, the two rubric score files, the retest file,
and text_prediction_results_r2_minilm.csv; writes
snippets/grid_numbers.tex (macros) and tables/tab_p1_grid.tex (the grid).
Registered in check_pipeline.py stage-5 like every producer.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
GRID = ROOT / "rubric_grid_analysis.csv"
PRED = ROOT / "text_prediction_results_r2_minilm.csv"
PRIM = ROOT / "rubric_grid_scores_gpt-4o-mini.csv"
RET = ROOT / "rubric_grid_scores_gpt-4o-mini_retest.csv"

def f3(x):
    return ("+" if x >= 0 else "") + f"{x:.2f}"

def main() -> None:
    g = pd.read_csv(GRID).set_index(["source", "dimension"])
    p = pd.read_csv(PRED)
    nat = p[(p["leg"] == "deconf") & p["sample"].isin(["espoused", "enacted"])
            & (p["arm"] == "tfidf")]

    def pcell(block, target):
        s = nat[(nat["block"] == block) & (nat["target"] == target)]
        return float(s["loo_r"].iloc[0])

    def pp(target):
        s = nat[(nat["block"] == "combined") & (nat["target"] == target)]
        return float(s["perm_p"].iloc[0])

    a = pd.read_csv(PRIM); b = pd.read_csv(RET)
    j = a.merge(b, on=["urn", "source", "dimension"], suffixes=("_1", "_2"))
    retest_all = (j["band_1"] == j["band_2"]).mean()

    m = {
        "PredWOfsted": f3(pcell("ofsted", "enacted_warmth")),
        "PredTOfsted": f3(pcell("ofsted", "enacted_teaching")),
        "PredSOfsted": f3(pcell("ofsted", "enacted_strictness")),
        "PredWCombined": f3(pcell("combined", "enacted_warmth")),
        "PredWCombinedP": f"{pp('enacted_warmth'):.3f}",
        "PredEspS": f3(pcell("combined", "espoused_strictness")),
        "PredEspClim": f3(pcell("combined", "espoused_staff_climate")),
        "PredEspW": f3(pcell("combined", "espoused_warmth")),
        "RubricSOfstedRaw": f3(g.loc[("ofsted", "strictness"), "rubric_raw"]),
        "RubricSOfstedDec": f3(g.loc[("ofsted", "strictness"), "rubric_deconf"]),
        "RubricWOfstedDec": f3(g.loc[("ofsted", "warmth"), "rubric_deconf"]),
        "RubricTOfstedDec": f3(g.loc[("ofsted", "teaching"), "rubric_deconf"]),
        "GridRetestExact": f"{retest_all:.0%}".replace("%", "\\%"),
        "RubricSSensAgree": f"{g.loc[('ofsted','strictness'),'sens_exact']:.0%}".replace("%", "\\%"),
    }
    lines = ["% generated by make_grid_numbers.py — do not edit"]
    for k, v in m.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    (HERE / "snippets" / "grid_numbers.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")

    rows = []
    order = [("ofsted", "warmth"), ("ofsted", "strictness"),
             ("ofsted", "teaching"), ("bp", "warmth"), ("bp", "strictness"),
             ("web", "warmth"), ("web", "strictness")]
    src_name = {"ofsted": "Inspection report", "bp": "Behaviour policy",
                "web": "Website"}
    tmap = {"warmth": "enacted_warmth", "strictness": "enacted_strictness",
            "teaching": "enacted_teaching"}
    for s, d in order:
        r = g.loc[(s, d)]
        model = pcell(s, tmap[d])
        rows.append(
            f"{src_name[s]} & {d.capitalize()} & {f3(model)} & "
            f"{f3(r['rubric_deconf'])} & {r['sens_exact']:.0%} & "
            f"{r['retest_exact']:.0%} \\\\".replace("%", "\\%"))
    table = r"""% generated by make_grid_numbers.py — do not edit
\begin{table}[htbp]
\centering
\caption{What each public text carries about enacted culture: two readings,
one criterion. Cells are correlations with the visit scores on the visited
schools ($n \approx 100$), with intake and report age partialled out of the
target. ``Agree'' is exact band agreement between the two language models
reading the same marking scheme; ``Retest'' is exact agreement on thirty
documents re-scored by the primary model.}
\label{tab:p1_grid}
\begin{tabular}{llcccc}
\toprule
Source & Dimension & Prediction model & Marking scheme & Agree & Retest \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    (HERE / "tables" / "tab_p1_grid.tex").write_text(table, encoding="utf-8")
    print(f"wrote grid_numbers.tex ({len(m)} macros) and tab_p1_grid.tex")

if __name__ == "__main__":
    main()
